name: Sync PR to GitLab

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # hoặc nhánh đích của PR trên GitHub

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0 

      - name: Set up Git config
        run: |
          git config --local user.name "Ngọc Thắng"
          git config --local user.email "thangcoiofficial@gmail.com"

      - name: Push code to GitLab
        env:
          GITLAB_REPO: https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/whitemousess/testcicd.git
        run: |
          git remote add gitlab $GITLAB_REPO
          git push gitlab HEAD:tmp-sync-branch --force

      - name: Auto merge using GitLab API
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl --request POST https://gitlab.com/api/v4/projects/69614878/merge_requests \
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --form "source_branch=tmp-sync-branch" \
          --form "target_branch=developer" \
          --form "title=Auto merge from GitHub PR" \
          --form "remove_source_branch=true" \
          --form "merge_when_pipeline_succeeds=true"